Feature/input and button
OasisUniverse/ui-library pull request #20
Opened 2021-12-20 18:53 UTC by s4d-prince

Input component
![image](https://user-images.githubusercontent.com/70597469/146818037-1b312ea7-e3d9-4a16-8094-570f3fe78831.png)

2021-12-20 19:17 UTC, alexandertumbasov requested changes

2021-12-20 19:17 UTC, alexandertumbasov commented on src/__mocks__/input.mock.tsx
> +        additionalElementsConfig: [
Забыл

2021-12-20 19:17 UTC, alexandertumbasov commented on .stylelintrc.json
>          "scss/dollar-variable-colon-space-after": "always",
Забыл добавить таблицу с тестами

2021-12-20 19:17 UTC, alexandertumbasov commented on src/__mocks__/input.mock.tsx
> +export const textInputProps: InputProps[] = [
Уголок у <textarea/>

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/button/button.component.tsx
> +export enum ButtonStyle {
Вынести в другую ветку

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.component.tsx
> +import ClosedEyeIcon from '../../shared/svg/closed-eye-icon';
import {ReactComponent} from './icon'

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.component.tsx
> +    TextInput,
DefaultInput

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.component.tsx
> +    const isRenderDisplayPasswordIcon = useMemo(
Очепятка

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.component.tsx
> +    const isRenderDisplayPasswordIcon = useMemo(
Все useState Должны быть наверху

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.component.tsx
> +    const displayPasswordHandler = () => {
Сделай в одну строку

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.component.tsx
> +    const hidingPasswordHandler = () => {
Тут тоже в одну строку

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.component.tsx
> +        (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => onChange(event.target.value),
Забыл добавить весь event

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.component.tsx
> +    const inputWrapperClassName = `${disabled ? styles.disabled : ''} ${disabled ? styles.disabled : ''} ${
useMemo

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.component.tsx
> +    const inputWrapperClassName = `${disabled ? styles.disabled : ''} ${disabled ? styles.disabled : ''} ${
Одно и тоже

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.component.tsx
> +        type !== InputType.TextArea ? styles.inputWrapper : ''
Лишнее условие

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.component.tsx
> +    } ${type === InputType.SearchInput ? styles.search : ''} ${value ? isActiveStyle : ''} ${
searchWrapper

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.component.tsx
> +    const inputWrapperClassName = `${disabled ? styles.disabled : ''} ${disabled ? styles.disabled : ''} ${
disabled должен быть в конце

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.component.tsx
> +                    className={`${isActiveStyle} ${disabled ? styles.disabled : ''} ${isErrorStyle} ${
Вынеси в переменную, часто код используется)

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.component.tsx
> +                            className={`${styles.passwordDisplayButton}`}
` можно убрать)

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.component.tsx
> +    const crossIcon = isRenderCrossIcon && (
isRenderCrossIcon лучше вынести вниз

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.module.scss
> +	flex-direction: column;
Убери

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.module.scss
> +	align-items: flex-start;
Убери

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.module.scss
> +			cursor: pointer;
Нужно cursor: pointer сделать для .cross

2021-12-20 19:17 UTC, alexandertumbasov commented on src/components/input/input.module.scss
> +			&.error {
Посмотри этот кейс, такое вообще возможно?

2021-12-20 19:17 UTC, alexandertumbasov commented on src/index.scss
> +	//font-family: 'PT Sans', sans-serif;
Поправь

2021-12-21 07:41 UTC, s4d-prince commented on src/components/input/input.component.tsx
> +import ClosedEyeIcon from '../../shared/svg/closed-eye-icon';
Не требуется, так как svg написан внутри компонента.
![image](https://user-images.githubusercontent.com/70597469/146890519-36933034-c7eb-4a6e-b459-78b03ceb87e5.png)

2021-12-21 07:59 UTC, s4d-prince commented on src/components/input/input.component.tsx
> +    const crossIcon = isRenderCrossIcon && (
Под `const crossIcon` ?

2021-12-21 08:07 UTC, s4d-prince commented on src/__mocks__/input.mock.tsx
> +export const textInputProps: InputProps[] = [
![image](https://user-images.githubusercontent.com/70597469/146893904-ffc5ffe8-4137-4fa1-8adf-a6714e487a87.png)

2021-12-21 09:16 UTC, s4d-prince commented on .stylelintrc.json
> +        "at-rule-no-unknown": null,
Это правило учитывает, что правила, определенные в Спецификациях CSS, вплоть до редакторских черновиков, должны быть известны.

2021-12-23 12:45 UTC, s4d-prince commented
Tests coverage
![image](https://user-images.githubusercontent.com/70597469/147242317-0650b292-223f-4462-8a67-74537943b977.png)

2021-12-23 13:55 UTC, alexandertumbasov approved these changes

2021-12-23 14:02 UTC, merged